### ISSUE TITLE
Hide all the API keys and tokens

### ISSUE THREAD

**Issue by prabhakar267** [AnirudhGoel/Chatbot#1]
You shouldn't be revealing all the tokens in your code.
https://github.com/AnirudhGoel/Chatbot/blob/master/chatbot.php#L3

**Comment by AnirudhGoel** [comment]
My site is hosted on Heroku. So, if I hide them on Github, it won't work on Heroku either. Help ?

**Comment by AnirudhGoel** [comment]
Done!
